# Generated by Django 5.2.15 on 2026-06-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_media_file_message_media_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='media_size',
            new_name='voice_duration',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_type',
        ),
        migrations.AddField(
            model_name='message',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
