# Generated by Django 5.2.15 on 2026-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_media_size_message_voice_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice_data',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_file_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_mime_type',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
